language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # R
  - sudo add-apt-repository -y ppa:marutter/rrutter
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # R
  - sudo apt-get install r-base r-base-dev
  - sudo Rscript -e 'install.packages(c("ape", "phytools", "DDD", "DAISIE"), repos = "http://cran.r-project.org")'
  #- sudo Rscript -e 'install.packages("DAISIE", repos = "http://cran.uk.r-project.org")'


script: 
  - qmake
  - make
  #- ./travis_qmake_gcc_cpp14_r_igraph
